apiVersion: v1
kind: ConfigMap
metadata:
  name: question-ms
  namespace: default
data:
  MONGODB_HOST: "mongodb-sharded-1573848232.default.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_PASS: "questions"
  MONGODB_USERNAME: "questions"
  MONGODB_DATABASE: "questions"
  MONGODB_AUTH: "questions"
  AUTHENTICATE_SERVICE: "authentication-service.default.svc.cluster.local:8080"